from turtle import *

def intro_paint():
     # Setup intro
    speed(6)
    penup()
    begin_fill()
    color("white")
    forward(-350)
    pendown()
    forward(700)
    right(90)
    forward(50)
    right(90)
    forward(700)
    right(90)
    forward(50)
    end_fill()

    penup()
    right(180)
    forward(40)
    left(90)
    forward(20)
    pendown()
    color("black")
    write("You now have the chance to give Dobby a new ending.\n",font=("Chalkboard", 14, "bold"))
    write("If you need to exit the program, just type 'quit'—but where's the fun in that? ",font=("Chalkboard", 14, "bold"))

def out_paint():
    clear()
    penup()
    setheading(0)
    goto(-300,20)
    pendown()

    begin_fill()
    color("black")
    forward(600)
    right(90)
    forward(40)
    right(90)
    forward(600)
    right(90)
    forward(40)
    end_fill()

    penup()
    right(180)
    forward(30)
    left(90)
    forward(20)
    pendown()
    color("pink")
    write("Congratulations! You've provided Dobby with a good life! ", font=("Chalkboard", 20, "bold"))